### ISSUE TITLE
Nuget package for GeoJSON.Net.Contrib.Wkb with Target Framework 4.5

### ISSUE THREAD

**Issue by tentakles** [GeoJSON-Net/GeoJSON.Net.Contrib#17]
Is it possible to create a Nuget-package for  GeoJSON.Net.Contrib.Wkb targeting .NET Framework 4.5 as well?

The current one requires .NET Framework 4.5.2 afaik.

Afaik, GeoJSON.Net and dependencies has packages targeting .NET Framework 4.5 as well.

thanks

**Comment by xfischer** [comment]
GC Wdis, which goes for "Good catch, Will do it soon" ;)

**Comment by xfischer** [comment]
Packages 0.1.2 targeting Net 45 released. Can you check if everything is OK ?
Thanks for the report @tentakles.

**Comment by tentakles** [comment]
Does not work for me im afraid;

Jetbrains Dotpeek tells me that thee packaged file in 0.1.2 still targets .Net framework v.4.5.2

See picture:

![geojsondotnetcontrib](https://user-images.githubusercontent.com/1454716/32283194-fb060bea-bf23-11e7-9998-d6dcdba4fa1c.PNG)

Also, when i try to compile my v4.5 app i get this error:

1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3274: The primary reference "GeoJSON.Net.Contrib.Wkb, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".

I also tried with an empty console app targeting v4.5 with just the geojson.net and contrib.wkb (v 0.12) and got the same error.

**Comment by xfischer** [comment]
Ok I’ll Check that tonight. Thanks for testing.

Le 1 nov. 2017 à 16:47, tentakles <notifications@github.com<mailto:notifications@github.com>> a écrit :


Does not work for me im afraid;

Jetbrains Dotpeek tells me that thee packaged file in 0.1.2 still targets .Net framework v.4.5.2

See picture:

[geojsondotnetcontrib]<https://user-images.githubusercontent.com/1454716/32283194-fb060bea-bf23-11e7-9998-d6dcdba4fa1c.PNG>

Also, when i try to compile my v4.5 app i get this error:

1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3274: The primary reference "GeoJSON.Net.Contrib.Wkb, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".

I also tried with an empty console app targeting v4.5 with just the geojson.net<http://geojson.net> and contrib.wkb (v 0.12) and got the same error.

**Comment by xfischer** [comment]
I've checked again and released nugets 0.1.3. Can you test again ?
Thanks

**Comment by tentakles** [comment]
Seems  to work great for me now :)

Thank you very much for fix and quick resolve.
